# Triggering conditions for the workflow
on:
  # Manual trigger with an input to specify the environment
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: environment
  schedule:
    - cron: '*/15 * * * *'

jobs:
  execute-job:
    runs-on:
      - self-hosted
      - ii-${{ matrix.environment }}
    strategy:
      matrix:
        environment: ${{ fromJson("[\"environment\":\"test\"]") }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Debug Variables
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Environment Input: ${{ github.event.inputs.environment }}"
          echo "Matrix Environment: ${{ matrix.environment }}"
      - name: Run Script
        run: |
          Write-Output "Deploying to ${{ matrix.environment }}"
          Write-Output "${{ vars.TEST }}"
        shell: pwsh
