# Triggering conditions for the workflow
on:
  # Manual trigger with an input to specify the environment
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: environment
  schedule:
    - cron: '*/15 * * * *'

jobs:
  execute-job:
    runs-on: [self-hosted, "ii-${{ github.event_name == 'schedule' && 'prod' || github.event.inputs.environment }}"]
    environment: ${{ github.event_name == 'schedule' && 'prod' || github.event.inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Script
        run: |
          write-output "Deploying to ${{ github.event_name == 'schedule' && 'prod' || github.event.inputs.environment }}"
          write-output "${{ vars.TEST }}"
          
        shell: pwsh
