# Triggering conditions for the workflow
on:
  # Manual trigger with an input to specify the environment
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: environment
  schedule:
    - cron: '*/15 * * * *'

jobs:
  execute-job:
    strategy:
      matrix:
        include: >-
          ${{ fromJson(github.event_name == 'schedule' ? '[{"environment": "prod"}, {"environment": "test"}]' : '[{"environment": "' + (github.event.inputs.environment || 'test') + '"}]')}}
    runs-on:
      - self-hosted
      - ii-${{ matrix.environment }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Script
        run: |
          Write-Output "Deploying to ${{ matrix.environment }}"
          Write-Output "${{ vars.TEST }}"
        shell: pwsh
